package com.ideacrest.parser.kotlin.anonymous

/**
 * Kotlin anonymous object and lambda fixture for testing source path mapping
 * of synthetic classes generated by the Kotlin compiler.
 *
 * The Kotlin parser should attribute synthetic class FQNs to:
 * 1. Anonymous object expressions: {@code object : SomeInterface { ... }}
 * 2. Lambda expressions that generate synthetic classes
 *
 * These should be registered as class vertices with proper source file mappings
 * so that the DOT graph renderer can generate valid URLs (not "null").
 */
interface TestInterface {
    fun execute(): String
}

class AnonymousObjectHolder {

    /**
     * Anonymous object expression implementing TestInterface.
     * Expected to generate a synthetic class like
     * {@code AnonymousObjectHolder$createAnonymous$1} or similar.
     */
    fun createAnonymous(): TestInterface {
        return object : TestInterface {
            override fun execute(): String = "anonymous"
        }
    }

    /**
     * Another anonymous object with a property.
     */
    fun createAnonymousWithProperty(): TestInterface {
        val captured = "captured"
        return object : TestInterface {
            override fun execute(): String = captured
        }
    }

    /**
     * Lambda expression - may generate a synthetic class.
     * Kotlin lambdas are typically compiled to synthetic classes like
     * {@code AnonymousObjectHolder$createLambda$1}.
     */
    fun createLambda(): () -> String {
        return { "lambda" }
    }

    /**
     * Lambda with captured variable.
     */
    fun createLambdaWithCapture(): () -> String {
        val captured = "captured-lambda"
        return { captured }
    }
}

/**
 * Top-level anonymous object (assigned to a property).
 * This should also generate a synthetic class.
 */
val topLevelAnonymous: TestInterface = object : TestInterface {
    override fun execute(): String = "top-level"
}