package org.hjug.feedback.vertex.kernelized;

import org.hjug.feedback.SuperTypeToken;
import org.jgrapht.Graph;
import java.util.Set;
import java.util.HashSet;

/**
 * Main facade for computing eta and k parameters needed for DirectedFeedbackVertexSetSolver
 * Generated by Perplexity.ai's Research model
 */
public class ParameterComputer<V, E> {

    private final TreewidthComputer<V, E> treewidthComputer;
    private final FeedbackVertexSetComputer<V, E> fvsComputer;

    public ParameterComputer(SuperTypeToken<E> edgeTypeToken) {
        this.treewidthComputer = new TreewidthComputer<>();
        this.fvsComputer = new FeedbackVertexSetComputer<>(edgeTypeToken);
    }

    public ParameterComputer(SuperTypeToken<E> edgeTypeToken, int parallelismLevel) {
        this.treewidthComputer = new TreewidthComputer<>(parallelismLevel);
        this.fvsComputer = new FeedbackVertexSetComputer<>(edgeTypeToken, parallelismLevel);
    }

    /**
     * Computes both eta and k parameters
     */
    public Parameters computeParameters(Graph<V, E> graph) {
        return computeParameters(graph, new HashSet<>());
    }

    /**
     * Computes eta and k with a given modulator
     */
    public Parameters computeParameters(Graph<V, E> graph, Set<V> modulator) {
        int eta = treewidthComputer.computeEta(graph, modulator);
        int k = fvsComputer.computeK(graph);

        return new Parameters(k, modulator.size(), eta);
    }

    /**
     * Computes a good modulator and then the parameters
     */
    public Parameters computeParametersWithOptimalModulator(Graph<V, E> graph, int maxModulatorSize) {
        Set<V> bestModulator = findGoodModulator(graph, maxModulatorSize);
        return computeParameters(graph, bestModulator);
    }

    /**
     * Finds a good treewidth modulator using various heuristics
     */
    private Set<V> findGoodModulator(Graph<V, E> graph, int maxSize) {
        if (maxSize <= 0) return new HashSet<>();

        // Try different modulator finding strategies
        Set<V> degreeBasedModulator = findDegreeBasedModulator(graph, maxSize);
        Set<V> fvsBasedModulator = findFeedbackVertexSetBasedModulator(graph, maxSize);

        // Choose the one that gives better treewidth
        int etaDegree = treewidthComputer.computeEta(graph, degreeBasedModulator);
        int etaFVS = treewidthComputer.computeEta(graph, fvsBasedModulator);

        return etaDegree <= etaFVS ? degreeBasedModulator : fvsBasedModulator;
    }

    private Set<V> findDegreeBasedModulator(Graph<V, E> graph, int maxSize) {
        return graph.vertexSet().parallelStream()
                .sorted((v1, v2) -> Integer.compare(
                        graph.inDegreeOf(v2) + graph.outDegreeOf(v2),
                        graph.inDegreeOf(v1) + graph.outDegreeOf(v1)))
                .limit(maxSize)
                .collect(java.util.stream.Collectors.toSet());
    }

    private Set<V> findFeedbackVertexSetBasedModulator(Graph<V, E> graph, int maxSize) {
        Set<V> fvs = fvsComputer.greedyFeedbackVertexSet(graph);
        if (fvs.size() <= maxSize) {
            return fvs;
        } else {
            return fvs.stream().limit(maxSize).collect(java.util.stream.Collectors.toSet());
        }
    }

    public void shutdown() {
        treewidthComputer.shutdown();
        fvsComputer.shutdown();
    }

    /**
     * Result container for computed parameters
     */
    public static class Parameters {
        private final int k;           // feedback vertex set size
        private final int modulatorSize; // modulator size (ℓ)
        private final int eta;         // treewidth after modulator removal

        public Parameters(int k, int modulatorSize, int eta) {
            this.k = k;
            this.modulatorSize = modulatorSize;
            this.eta = eta;
        }

        public int getK() { return k; }
        public int getModulatorSize() { return modulatorSize; }
        public int getEta() { return eta; }

        @Override
        public String toString() {
            return String.format("Parameters{k=%d, ℓ=%d, η=%d}", k, modulatorSize, eta);
        }
    }
}
